import * as core from '@actions/core'
import { exec } from 'child_process'
import fs from 'fs'
import path from 'path'
import { promisify } from 'util'

const execAsync = promisify(exec)

const botsToSkip = new Set([
  'Copilot',
  'SourceryAI',
  'Copilot Autofix powered by AI'
])
const botPattern = /\[bot\]$/

const authorsToMerge: Record<string, string> = {
  rlauu: 'rlauuzo',
  'Abandoned Cart': 'AbandonedCart',
  TwistedUmbrellaX: 'AbandonedCart',
  jumoog: 'Kilian von Pflugk'
}

interface YearRange {
  firstYear: number
  lastYear: number
}

function processAuthor(
  authorYears: Map<string, YearRange>,
  author: string,
  date: string
): void {
  if (botsToSkip.has(author) || botPattern.test(author)) return

  const resolvedAuthor = authorsToMerge[author] ?? author
  const year = parseInt(date.substring(0, 4), 10)

  const existing = authorYears.get(resolvedAuthor)
  if (!existing) {
    authorYears.set(resolvedAuthor, { firstYear: year, lastYear: year })
  } else {
    existing.firstYear = Math.min(existing.firstYear, year)
    existing.lastYear = Math.max(existing.lastYear, year)
  }
}

function* walkCsFiles(dir: string): Generator<string> {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      if (entry.name !== 'obj') yield* walkCsFiles(fullPath)
    } else if (entry.isFile() && entry.name.endsWith('.cs')) {
      yield fullPath
    }
  }
}

async function processFile(filePath: string, rootDir: string): Promise<void> {
  const relativePath = path.relative(rootDir, filePath).replace(/\\/g, '/')

  const fileContent = fs.readFileSync(filePath, 'utf8')
  const firstTwoLines = fileContent.split('\n').slice(0, 2).join('\n')
  if (firstTwoLines.includes('// <auto-generated />')) {
    core.info(`Skipping auto-generated: ${relativePath}`)
    return
  }

  core.info(`Processing: ${relativePath}`)

  let gitOutput: string
  try {
    const result = await execAsync(
      `git log --follow --format="%an|%ad|%B" --date=short -- "${relativePath}"`,
      { encoding: 'utf8', cwd: rootDir }
    )
    gitOutput = result.stdout
  } catch {
    core.warning(`Failed to get git log for ${relativePath}`)
    return
  }

  const authorYears = new Map<string, YearRange>()
  const lines = gitOutput.split('\n')

  let currentAuthor = ''
  let currentDate = ''
  let messageBuffer: string[] = []

  const commitLineRegex = /^([^|]+)\|(\d{4}-\d{2}-\d{2})\|(.*)$/

  const flushCoAuthors = (): void => {
    if (!currentAuthor) return
    const fullMessage = messageBuffer.join('\n')
    for (const coMatch of fullMessage.matchAll(
      /Co-authored-by:\s*([^<]+)<[^>]+>/g
    )) {
      processAuthor(authorYears, coMatch[1].trim(), currentDate)
    }
  }

  for (const line of lines) {
    const match = commitLineRegex.exec(line)
    if (match) {
      flushCoAuthors()
      currentAuthor = match[1]
      currentDate = match[2]
      messageBuffer = [match[3]]
      processAuthor(authorYears, currentAuthor, currentDate)
    } else {
      messageBuffer.push(line)
    }
  }
  flushCoAuthors()

  if (authorYears.size === 0) {
    core.info(`  No human authors found, skipping...`)
    return
  }

  const sortedAuthors = [...authorYears.entries()]
    .sort((a, b) => a[1].firstYear - b[1].firstYear)
    .map(([author]) => author)

  core.info(`  Human authors: ${sortedAuthors.length}`)

  // Strip existing SPDX header block
  const contentLines = fileContent.split(/\r?\n/)
  const newLines: string[] = []
  let skipMode = false

  for (const line of contentLines) {
    if (line.includes('// SPDX-FileCopyrightText:')) {
      skipMode = true
      continue
    }
    if (line.includes('// SPDX-License-Identifier:')) {
      skipMode = false
      continue
    }
    if (skipMode && line.trim() === '') continue
    if (line.includes('Intro-Skipper contributors')) continue
    skipMode = false
    newLines.push(line)
  }

  const headerLines = sortedAuthors.map((author) => {
    const years = authorYears.get(author)!
    const yearStr =
      years.firstYear === years.lastYear
        ? `${years.firstYear}`
        : `${years.firstYear}-${years.lastYear}`
    return `// SPDX-FileCopyrightText: ${yearStr} ${author}`
  })
  headerLines.push('// SPDX-License-Identifier: GPL-3.0-only')

  let newContent = headerLines.join('\n') + '\n' + newLines.join('\n')

  if (fileContent.includes('\r\n')) {
    newContent = newContent.replace(/\r\n/g, '\n').replace(/\n/g, '\r\n')
  }

  fs.writeFileSync(filePath, newContent, { encoding: 'utf8' })
  core.info(`  Updated with ${sortedAuthors.length} human authors!`)
}

export async function addSpdxHeaders(rootDir = '.'): Promise<void> {
  const csFiles = [...walkCsFiles(rootDir)]
  await Promise.all(csFiles.map((filePath) => processFile(filePath, rootDir)))
  core.info('Done!')
}
